// Gets the id of the link that was pressed which was generated by php and posts as ajax to server so it can check the id and change the resource dir to match.
function loadQuiz(courseName){
    var xhttp = new XMLHttpRequest();

    xhttp.onreadystatechange = function(){
        if(xhttp.readyState == 4 && xhttp.status == 200){
            var result = xhttp.responseText;
            document.getElementById("mycoursesDashboard").innerHTML = result;
            console.log(result);
        }
    }
   
    xhttp.open("GET", "studentQuiz.php?courseName=" + courseName, true);
    xhttp.send();
}